# Generated by Django 3.2.13 on 2023-06-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflashcards',
            name='flashcard',
        ),
        migrations.RemoveField(
            model_name='userflashcards',
            name='user',
        ),
        migrations.DeleteModel(
            name='Flashcards',
        ),
        migrations.DeleteModel(
            name='UserFlashcards',
        ),
    ]
